import { Product } from "@/types/product";

const shopData: Product[] = [
  {
    id: 1,
    title: "Corrugated Cardboard Production Line",
    category: "Packaging & Corrugation Machinery",
    subCategory: "Turnkey Line",
    description: "A complete production line for corrugated cardboard, supplied as a matched set from reel stand to stacker. The 3-ply, 5-ply, 7-ply and multi-function configurations are built from the same core modules \u2014 mill roll stand, pre-heater, single facer, conveying bridge, glue application machine, double facer, slitter scorer, cut-off, conveyor and stacker \u2014 together with the heating, air compression and glue making systems.",
    specifications: [
      { label: "Model", value: "KG-CL Series" },
      { label: "Line speed", value: "100 \u2013 220 m/min" },
      { label: "Paper width", value: "1400 \u2013 2200 mm" },
      { label: "Flute profiles", value: "A, B, C, E (UV type)" },
      { label: "Ply configuration", value: "3 / 5 / 7 ply and multi-function" },
      { label: "Heating", value: "Steam / electric / thermic oil" },
      { label: "Line grades", value: "High, middle and economy build" },
      { label: "Line modules", value: "Mill roll stand, paper pre-heater, single facer, conveying bridge, glue application machine, double facer, slitter scorer, cut-off, conveyor & stacker, heating system, air compression system, glue making system" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/corrugated-cardboard-production-line-1-1.jpeg"],
      previews: ["/images/catalogue/corrugated-cardboard-production-line-1-1.jpeg"],
    },
  },
  {
    id: 2,
    title: "Electric Mill Roll Stand",
    category: "Packaging & Corrugation Machinery",
    subCategory: "Reel Handling",
    description: "Cast-iron reel stand for single-side loading in motorised build, with fully motorised lift, lower, clamp, loosen and traverse movement and pneumatic brake tension control for stable web tension into the pre-heater.",
    specifications: [
      { label: "Model", value: "KG-MRS/E" },
      { label: "Max. reel diameter", value: "\u03a6 1500 mm" },
      { label: "One-side loading", value: "Max. 1500 kg" },
      { label: "Arm control motor (clamp)", value: "0.37 kW" },
      { label: "Arm control motor (swing)", value: "1.5 kW" },
      { label: "Wallboard and arm", value: "Iron cast" },
      { label: "Control", value: "Fully motorised \u2014 lift, lower, clamp, loosen, movement, contraposition" },
      { label: "Tension control", value: "Pneumatic brake, manual control" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/electric-mill-roll-stand-2-1.jpeg"],
      previews: ["/images/catalogue/electric-mill-roll-stand-2-1.jpeg"],
    },
  },
  {
    id: 3,
    title: "Hydraulic Mill Roll Stand",
    category: "Packaging & Corrugation Machinery",
    subCategory: "Reel Handling",
    description: "Cast-iron reel stand for single-side loading in hydraulic build, carrying double-point or multi-point braking for stable web tension into the pre-heater.",
    specifications: [
      { label: "Model", value: "KG-MRS/H" },
      { label: "Max. reel diameter", value: "\u03a6 1500 mm" },
      { label: "One-side loading", value: "Max. 3000 kg" },
      { label: "Hydraulic station motor", value: "4.0 kW (continuous working)" },
      { label: "Wallboard and arm", value: "Iron cast" },
      { label: "Hydraulic control", value: "Paper lifting / lowering, clamping / releasing, left-right movement" },
      { label: "Brake style", value: "Double-point or multi-point type" },
      { label: "Over-paper roller", value: "\u03a6219 (1600) / \u03a6245 (1800) / \u03a6270 (2200) mm" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/hydraulic-mill-roll-stand-3-1.jpeg"],
      previews: ["/images/catalogue/hydraulic-mill-roll-stand-3-1.jpeg"],
    },
  },
  {
    id: 4,
    title: "Paper Pre-Heat Cylinder",
    category: "Packaging & Corrugation Machinery",
    subCategory: "Web Conditioning",
    description: "Steam-heated drums condition the liner and medium before corrugation and gluing, driving out moisture and stabilising the web. Wrap angle is adjustable through a full 360\u00b0 rotation so the heated contact area can be tuned to paper grade and line speed. Offered in single, double and triple drum configurations.",
    specifications: [
      { label: "Model", value: "KG-PH" },
      { label: "Effective width", value: "1400 \u2013 2500 mm" },
      { label: "Angle adjustment range", value: "360\u00b0 rotation" },
      { label: "Steam temperature", value: "150 \u2013 180 \u00b0C" },
      { label: "Motor power", value: "0.37 kW" },
      { label: "Pre-heat roller diameter", value: "\u03a6600 / \u03a6900 / \u03a61000 mm" },
      { label: "Angle shaft diameter", value: "\u03a687 mm \u00d7 2" },
      { label: "Steam pressure", value: "0.8 \u2013 1.3 MPa" },
      { label: "Rotary type", value: "Autorotation or passive rotation" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/paper-pre-heat-cylinder-4-1.jpeg", "/images/catalogue/paper-pre-heat-cylinder-4-2.jpeg", "/images/catalogue/paper-pre-heat-cylinder-4-3.jpeg"],
      previews: ["/images/catalogue/paper-pre-heat-cylinder-4-1.jpeg", "/images/catalogue/paper-pre-heat-cylinder-4-2.jpeg", "/images/catalogue/paper-pre-heat-cylinder-4-3.jpeg"],
    },
  },
  {
    id: 5,
    title: "Fingerless Type Single Facer",
    category: "Packaging & Corrugation Machinery",
    subCategory: "Corrugation",
    description: "Vacuum-assisted fingerless corrugation removes the finger marks that limit print quality on the finished board and allows higher sustained speeds. Corrugating rollers are ground from 48CrMo or 52CrMo alloy steel and the machine is offered in oblique or square wallboard construction with gearbox or chain transmission.",
    specifications: [
      { label: "Model", value: "KG-270 / 280 / 320 / 360 / 380" },
      { label: "Working width", value: "1400 \u2013 2300 mm" },
      { label: "Design speed", value: "100 \u2013 200 m/min" },
      { label: "Upper corrugated roller", value: "\u03a6280 \u2013 \u03a6350 mm" },
      { label: "Lower corrugated roller", value: "\u03a6280 \u2013 \u03a6380 mm" },
      { label: "Main driving motor", value: "11 \u2013 30 kW" },
      { label: "Heating type", value: "Steam / electric / oil" },
      { label: "Corrugating roller", value: "48CrMo or 52CrMo alloy steel" },
      { label: "Wallboard type", value: "Oblique / square" },
      { label: "Transmission", value: "Gear box / chain" },
      { label: "Feeding type", value: "Fingerless / finger" },
      { label: "Control", value: "VFD inverter control" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/fingerless-type-single-facer-5-1.jpeg"],
      previews: ["/images/catalogue/fingerless-type-single-facer-5-1.jpeg"],
    },
  },
  {
    id: 6,
    title: "Glue Application Machine",
    category: "Packaging & Corrugation Machinery",
    subCategory: "Lamination",
    description: "Glue application and web storage between the single facer and the double facer. Roller diameters are matched to line speed so that glue film weight stays consistent as the line accelerates. Contact bar assemblies, glue dispensing pumps and steam traps supplied to the same specification as the line.",
    specifications: [
      { label: "Model", value: "KG-GM" },
      { label: "Pre-heater temperature range", value: "> 200 \u00b0C" },
      { label: "Steam pressure", value: "0.8 \u2013 1.2 MPa" },
      { label: "Air source system", value: "0.4 \u2013 0.7 MPa" },
      { label: "Glue roller", value: "\u03a6216 mm / \u03a6240 mm" },
      { label: "Fixed paste roller", value: "\u03a6114 mm" },
      { label: "Lower / upper pre-heat roller", value: "\u03a6300 mm / \u03a6402 mm" },
      { label: "Over-paper roller", value: "\u03a689 mm" },
      { label: "Glue roller motor", value: "3 kW frequency motor" },
      { label: "Glue pump motor", value: "2.2 kW" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/glue-application-machine-6-1.jpeg"],
      previews: ["/images/catalogue/glue-application-machine-6-1.jpeg"],
    },
  },
  {
    id: 7,
    title: "Conveying Bridge",
    category: "Packaging & Corrugation Machinery",
    subCategory: "Lamination",
    description: "Buffer storage of the single-faced web between the single facer and double facer, on a bolted steel gantry with walkway access. Web guidance is by powered belt conveyor with tension control, PLC and touch screen operation.",
    specifications: [
      { label: "Model", value: "KG-OB" },
      { label: "Function", value: "Buffer storage of single-faced web" },
      { label: "Web guidance", value: "Powered belt conveyor with tension control" },
      { label: "Construction", value: "Bolted steel gantry, walkway ready" },
      { label: "Glue roller / paste roller", value: "45 quenching steel" },
      { label: "Pre-heat roller", value: "Q235B container board" },
      { label: "Touch screen", value: "Industrial HMI" },
      { label: "PLC and frequency drive", value: "Reputed make to specification" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/conveying-bridge-7-1.jpeg"],
      previews: ["/images/catalogue/conveying-bridge-7-1.jpeg"],
    },
  },
  {
    id: 8,
    title: "Double Facer \u2014 Heavy Type",
    category: "Packaging & Corrugation Machinery",
    subCategory: "Lamination",
    description: "The double facer bonds the outer liner to the single-faced web across a heated plate section under controlled belt pressure. Heavy 300 mm main-body wallboards keep the frame stable at high speed, and the thermal bar option replaces conventional press rollers to lift board flatness and bond quality.",
    specifications: [
      { label: "Model", value: "KG-DF (Heavy Type)" },
      { label: "Working width", value: "1400 \u2013 2400 mm" },
      { label: "Upper driving roller", value: "500 mm, 840 mm for choice" },
      { label: "Down driving roller", value: "500 mm, 630 mm for choice" },
      { label: "Wallboard of main drive part", value: "200 mm" },
      { label: "Wallboard of main body", value: "300 mm" },
      { label: "Hot plate", value: "595 mm (width) \u00d7 30 mm (thickness), 9 \u2013 22 pcs for choice" },
      { label: "Belt / felt", value: "Cotton felt or needled felt" },
      { label: "Rotary joint", value: "Precision steam joint" },
      { label: "Thermal bar \u2014 suitable speed", value: "\u2264 250 m/min" },
      { label: "Thermal bar \u2014 working life", value: "More than 20 years" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/double-facer-heavy-type-8-1.jpeg"],
      previews: ["/images/catalogue/double-facer-heavy-type-8-1.jpeg"],
    },
  },
  {
    id: 9,
    title: "NC Slitter Scorer",
    category: "Packaging & Corrugation Machinery",
    subCategory: "Web Finishing",
    description: "Numerically controlled blade and crease positioning for fast order change on the dry end of the line.",
    specifications: [
      { label: "Model", value: "KG-NCS" },
      { label: "Effective width", value: "1400 \u2013 2200 mm" },
      { label: "Design speed", value: "100 m/min" },
      { label: "Cutting precision", value: "\u00b1 1 mm" },
      { label: "Motor power", value: "Main 11 kW, assistant 2.2 kW" },
      { label: "Motor type", value: "Frequency motor" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/nc-slitter-scorer-9-1.jpeg"],
      previews: ["/images/catalogue/nc-slitter-scorer-9-1.jpeg"],
    },
  },
  {
    id: 10,
    title: "Lift-Down Type Slitter Scorer",
    category: "Packaging & Corrugation Machinery",
    subCategory: "Web Finishing",
    description: "Lift-down knife carrier for quick blade set changes on shorter runs, thin-blade slitting and creasing for the dry end of the line.",
    specifications: [
      { label: "Model", value: "KG-SZ" },
      { label: "Effective width", value: "1400 \u2013 2200 mm" },
      { label: "Design speed", value: "100 m/min" },
      { label: "Cutting precision", value: "\u00b1 1 mm" },
      { label: "Knife shaft diameter", value: "200 mm" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/lift-down-type-slitter-scorer-10-1.jpeg"],
      previews: ["/images/catalogue/lift-down-type-slitter-scorer-10-1.jpeg"],
    },
  },
  {
    id: 11,
    title: "Manual / Electric Blade Adjust Slitter Scorer",
    category: "Packaging & Corrugation Machinery",
    subCategory: "Web Finishing",
    description: "Economy build slitter scorer with manual or electrically assisted blade positioning for thin-blade slitting and creasing.",
    specifications: [
      { label: "Model", value: "KG-DDP" },
      { label: "Effective width", value: "1400 \u2013 2200 mm" },
      { label: "Design speed", value: "100 m/min" },
      { label: "Wallboard thickness", value: "30 mm" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/manual-electric-blade-adjust-slitter-sco-11-1.jpeg"],
      previews: ["/images/catalogue/manual-electric-blade-adjust-slitter-sco-11-1.jpeg"],
    },
  },
  {
    id: 12,
    title: "High Speed Spiral Knife Cut-Off",
    category: "Packaging & Corrugation Machinery",
    subCategory: "Web Finishing",
    description: "Single or double layer spiral blade cut-off for high-speed cross cutting at the dry end of the line.",
    specifications: [
      { label: "Model", value: "KG-SKC" },
      { label: "Effective width", value: "1400 \u2013 2200 mm" },
      { label: "Design speed", value: "100 \u2013 200 m/min" },
      { label: "Cutting length", value: "400 \u2013 9900 mm" },
      { label: "Cutting precision", value: "\u00b1 1 mm" },
      { label: "Knife shaft diameter", value: "198 mm" },
      { label: "Wallboard thickness", value: "35 \u2013 50 mm for choice" },
      { label: "Motor power", value: "11 \u2013 30 kW for choice" },
      { label: "Motor type", value: "Servo motor" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/high-speed-spiral-knife-cut-off-12-1.jpeg"],
      previews: ["/images/catalogue/high-speed-spiral-knife-cut-off-12-1.jpeg"],
    },
  },
  {
    id: 13,
    title: "NC Cut-Off",
    category: "Packaging & Corrugation Machinery",
    subCategory: "Line Discharge",
    description: "Cross cutting to length at the end of the line, with servo or frequency drive depending on required speed and cut accuracy.",
    specifications: [
      { label: "Model", value: "KG-NCO" },
      { label: "Effective width", value: "1400 \u2013 2200 mm" },
      { label: "Design speed", value: "100 \u2013 200 m/min" },
      { label: "Cutting length", value: "400 \u2013 9900 mm" },
      { label: "Cutting precision", value: "\u00b1 1 mm" },
      { label: "Blade type", value: "Straight or spiral blade" },
      { label: "Motor type", value: "Frequency or servo motor" },
      { label: "Touch screen", value: "Industrial HMI" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/nc-cut-off-13-1.jpeg"],
      previews: ["/images/catalogue/nc-cut-off-13-1.jpeg"],
    },
  },
  {
    id: 14,
    title: "Automatic / Semi-Auto Stacker",
    category: "Packaging & Corrugation Machinery",
    subCategory: "Line Discharge",
    description: "Automatic sheet collection and stacking at the end of the line, in automatic and semi-automatic variants with powered belt conveyor and lift table discharge.",
    specifications: [
      { label: "Model", value: "KG-ST" },
      { label: "Function", value: "Automatic sheet collection and stacking" },
      { label: "Build", value: "Automatic and semi-automatic variants" },
      { label: "Discharge", value: "Powered belt conveyor with lift table" },
      { label: "Stack height", value: "To customer requirement" },
      { label: "Control", value: "PLC with touch screen" },
      { label: "Safety", value: "Guarded gantry with access walkway" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/automatic-semi-auto-stacker-14-1.jpeg"],
      previews: ["/images/catalogue/automatic-semi-auto-stacker-14-1.jpeg"],
    },
  },
  {
    id: 15,
    title: "Automatic High Speed Printing, Slotting & Die-Cutting Machine",
    category: "Packaging & Corrugation Machinery",
    subCategory: "Converting",
    description: "Lead-edge feeding, flexo printing, slotting and rotary die-cutting in one pass, with colour groups configured to requirement. Phase adjustment on every unit is motorised, so register is recovered without stopping the line.",
    specifications: [
      { label: "Model", value: "KG-900 / 1200 / 1400" },
      { label: "Printing roller diameter", value: "300 \u2013 480 mm" },
      { label: "Production speed", value: "120 \u2013 200 pcs/min" },
      { label: "Max. paper size", value: "900 \u00d7 2600 \u2013 1400 \u00d7 2600 mm" },
      { label: "Min. paper size (positive knife)", value: "300 \u00d7 640 \u2013 400 \u00d7 720 mm" },
      { label: "Max. printing size", value: "900 \u00d7 2400 \u2013 1400 \u00d7 2400 mm" },
      { label: "Max. die-cutting size", value: "900 \u00d7 2500 \u2013 1400 \u00d7 2500 mm" },
      { label: "Slot width \u00d7 max. depth", value: "7 \u00d7 220 \u2013 7 \u00d7 350 mm" },
      { label: "Control mode", value: "PLC / touch screen / button" },
      { label: "Printing paper", value: "A, B, C, A/B, B/C, A/B/C" },
      { label: "Max. printing plate thickness", value: "7.2 mm" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/automatic-high-speed-printing-slotting-d-15-1.jpeg"],
      previews: ["/images/catalogue/automatic-high-speed-printing-slotting-d-15-1.jpeg"],
    },
  },
  {
    id: 16,
    title: "Semi-Auto Flexo Printing Slotting Die-Cutting Machine",
    category: "Packaging & Corrugation Machinery",
    subCategory: "Converting",
    description: "Economy converting for shorter runs and mixed order books \u2014 semi-automatic flexo printing with slotting and die-cutting. Three-minute order change and batch counter.",
    specifications: [
      { label: "Model", value: "KG-VT Series" },
      { label: "Feeding size", value: "1800 \u00d7 900 \u2013 2800 \u00d7 1600 mm" },
      { label: "Printing size", value: "1600 \u00d7 900 \u2013 2600 \u00d7 1600 mm" },
      { label: "Working speed", value: "0 \u2013 100 pcs/min" },
      { label: "Board thickness", value: "11 mm" },
      { label: "Main power", value: "5.5 / 7.5 / 11 kW" },
      { label: "Roller diameter", value: "300 / 408 / 480 / 530 mm" },
      { label: "Models", value: "VT-2000 to VT-3000" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/semi-auto-flexo-printing-slotting-die-cu-16-1.jpeg"],
      previews: ["/images/catalogue/semi-auto-flexo-printing-slotting-die-cu-16-1.jpeg"],
    },
  },
  {
    id: 17,
    title: "Semi-Auto Servo-Drive Stitcher with Auto Wire Feeder",
    category: "Packaging & Corrugation Machinery",
    subCategory: "Converting",
    description: "Servo-driven box stitcher with automatic wire feed, automatic batch ejector, batch counter and manual checking function.",
    specifications: [
      { label: "Model", value: "KG-AS/016A" },
      { label: "Machine speed", value: "428 stitches/min" },
      { label: "Stitching modes", value: "Single pin, tag stitch, double pin" },
      { label: "Board thickness", value: "3 \u2013 8 mm single / double wall" },
      { label: "Wire length", value: "36 \u2013 37 mm" },
      { label: "Wire spool capacity", value: "2 kg" },
      { label: "Max. (L+W) \u00d7 2", value: "3700 mm" },
      { label: "Min. (L+W) \u00d7 2", value: "480 mm" },
      { label: "Stitching pitch", value: "30 \u2013 110 mm" },
      { label: "Feeder height", value: "900 mm" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/semi-auto-servo-drive-stitcher-with-auto-17-1.jpeg"],
      previews: ["/images/catalogue/semi-auto-servo-drive-stitcher-with-auto-17-1.jpeg"],
    },
  },
  {
    id: 18,
    title: "Automatic Folder Gluer Machine",
    category: "Packaging & Corrugation Machinery",
    subCategory: "Converting",
    description: "Automatic folder gluer for regular slotted cartons, with PLC and touch screen control and electrical parts to reputed makes.",
    specifications: [
      { label: "Model", value: "KG-2400 / KG-2500" },
      { label: "Max. cardboard", value: "900 \u00d7 2200 mm / 1200 \u00d7 2500 mm" },
      { label: "Min. cardboard", value: "300 \u00d7 900 mm" },
      { label: "Dimensions", value: "L11000\u00d7W3000\u00d7H1600 mm / L12500\u00d7W3200\u00d7H1600 mm" },
      { label: "Total weight", value: "5500 kg / 6500 kg" },
      { label: "Power required", value: "12 kW, 380 V, 3 phase, 50 Hz" },
      { label: "Paperboard thickness", value: "3 or 5 layer" },
      { label: "Control", value: "PLC and touch screen" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/automatic-folder-gluer-machine-18-1.jpeg"],
      previews: ["/images/catalogue/automatic-folder-gluer-machine-18-1.jpeg"],
    },
  },
  {
    id: 19,
    title: "Semi-Auto Folder Gluer",
    category: "Packaging & Corrugation Machinery",
    subCategory: "Converting",
    description: "Semi-automatic folder gluer for regular slotted cartons, with PLC operator panel control.",
    specifications: [
      { label: "Model", value: "KG-SG" },
      { label: "Blank width (W)", value: "180 \u2013 450 mm" },
      { label: "Blank length (L)", value: "270 \u2013 650 mm" },
      { label: "Blank depth (D2)", value: "300 \u2013 900 mm" },
      { label: "Glue flap (G)", value: "35 \u2013 40 mm" },
      { label: "Max. sheet", value: "2600 mm" },
      { label: "Min. sheet", value: "606 mm" },
      { label: "Control", value: "PLC with operator panel" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/semi-auto-folder-gluer-19-1.jpeg"],
      previews: ["/images/catalogue/semi-auto-folder-gluer-19-1.jpeg"],
    },
  },
  {
    id: 20,
    title: "Automatic Flute Laminator",
    category: "Packaging & Corrugation Machinery",
    subCategory: "Converting",
    description: "Fully automatic litho-lamination of printed top sheet onto single-faced board, with top feeding, bottom feeding, transmission, locating and adjustment units supplied as matched assemblies.",
    specifications: [
      { label: "Model", value: "KG-1300 / 1450 / 1600" },
      { label: "Maximum size", value: "1100\u00d71300 / 1100\u00d71450 / 1400\u00d71600 mm" },
      { label: "Minimum size", value: "350\u00d7350 / 350\u00d7350 / 450\u00d7450 mm" },
      { label: "Laminate precision", value: "\u2264 \u00b1 1.5 mm" },
      { label: "Speed", value: "6000 sheets/h" },
      { label: "Total power", value: "12 kW / 12 kW / 13 kW" },
      { label: "Length", value: "12.5 m / 12.5 m / 15 m" },
      { label: "Total weight", value: "6.8 T / 7.2 T / 8.0 T" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/automatic-flute-laminator-20-1.jpeg"],
      previews: ["/images/catalogue/automatic-flute-laminator-20-1.jpeg"],
    },
  },
  {
    id: 21,
    title: "Semi-Auto Flute Laminator",
    category: "Packaging & Corrugation Machinery",
    subCategory: "Converting",
    description: "Semi-automatic litho-lamination of printed top sheet onto single-faced board, compact footprint for shorter runs.",
    specifications: [
      { label: "Model", value: "KG-Q-2" },
      { label: "Maximum sheet size", value: "1300\u00d71300 / 1450\u00d71300 / 1600\u00d71300 mm" },
      { label: "Minimum sheet size", value: "350 \u00d7 450 mm" },
      { label: "Speed", value: "0 \u2013 90 m/min" },
      { label: "Total power", value: "7 kW" },
      { label: "Overall dimensions", value: "8.8 \u00d7 2.2 \u00d7 1.7 m (approx.)" },
      { label: "Total weight", value: "3.5 \u2013 4.5 T" },
      { label: "Conveyor belt", value: "PVC" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/semi-auto-flute-laminator-21-1.jpeg"],
      previews: ["/images/catalogue/semi-auto-flute-laminator-21-1.jpeg"],
    },
  },
  {
    id: 22,
    title: "Die Cutting, Slotting & Feeding Equipment",
    category: "Packaging & Corrugation Machinery",
    subCategory: "Converting",
    description: "Flat-bed and rotary die cutting, sheet cutting, rotary slotting and infeed equipment for carton plants running mixed board grades.",
    specifications: [
      { label: "Automatic Die Cutting & Creasing Machine (KG-1060/1080/1100/1200)", value: "Flat-bed automatic die cutting and creasing with gripper feed and guarded platform" },
      { label: "NC Sheet Cutter with Stacker (KG-NSC)", value: "Numerically controlled sheet cutting with integrated stacking" },
      { label: "Chain Feeding Rotary Die Cutting Machine (KG-CRD)", value: "Chain-fed rotary die cutter for economical medium-run production" },
      { label: "Chain Feeding Rotary Slotting Machine (KG-CRS)", value: "Rotary slotting with chain feed for regular slotted carton work" },
      { label: "Platen Die-Punching Heavy Duty Machine (KG-PDP)", value: "Heavy-duty platen die punching for thick and double-wall board" },
      { label: "Auto Feeding Machine (KG-AF)", value: "Automatic sheet infeed unit to keep converting lines continuously fed" },
      { label: "Pressing Type Fold Gluer (KG-PFG)", value: "Pressing type folding and gluing for straight-line cartons" },
      { label: "Flat-Bed Die Cutter \u2014 Platform Type (KG-FBD)", value: "Heavy platform flat-bed die cutting and creasing for large blanks" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/die-cutting-slotting-feeding-equipment-22-1.jpeg", "/images/catalogue/die-cutting-slotting-feeding-equipment-22-2.jpeg", "/images/catalogue/die-cutting-slotting-feeding-equipment-22-3.jpeg", "/images/catalogue/die-cutting-slotting-feeding-equipment-22-4.jpeg", "/images/catalogue/die-cutting-slotting-feeding-equipment-22-5.jpeg", "/images/catalogue/die-cutting-slotting-feeding-equipment-22-6.jpeg", "/images/catalogue/die-cutting-slotting-feeding-equipment-22-7.jpeg", "/images/catalogue/die-cutting-slotting-feeding-equipment-22-8.jpeg"],
      previews: ["/images/catalogue/die-cutting-slotting-feeding-equipment-22-1.jpeg", "/images/catalogue/die-cutting-slotting-feeding-equipment-22-2.jpeg", "/images/catalogue/die-cutting-slotting-feeding-equipment-22-3.jpeg", "/images/catalogue/die-cutting-slotting-feeding-equipment-22-4.jpeg", "/images/catalogue/die-cutting-slotting-feeding-equipment-22-5.jpeg", "/images/catalogue/die-cutting-slotting-feeding-equipment-22-6.jpeg", "/images/catalogue/die-cutting-slotting-feeding-equipment-22-7.jpeg", "/images/catalogue/die-cutting-slotting-feeding-equipment-22-8.jpeg"],
    },
  },
  {
    id: 23,
    title: "Carton Plant Machinery",
    category: "Packaging & Corrugation Machinery",
    subCategory: "Plant Equipment",
    description: "Ancillary and stand-alone machinery for corrugated box plants \u2014 board handling, waste recovery, pasting, strapping and printing.",
    specifications: [
      { label: "Strapping Machine \u2014 Type A (KG-STR/A)", value: "Vertical baling and strapping press for bundled output" },
      { label: "Strapping Machine \u2014 Type B (KG-STR/B)", value: "Semi-automatic strapping unit with reel holder" },
      { label: "Clapboard / Partition Machine (KG-CB)", value: "Slotting and assembly of board partitions and dividers" },
      { label: "Shredder Motor Unit (KG-SHR)", value: "Waste board shredding and pneumatic conveying unit" },
      { label: "Pasting Machine (KG-PST)", value: "Roller pasting machine for sheet lamination and manual lines" },
      { label: "Flexo Printing Machine (KG-FP)", value: "Stand-alone flexo printing unit for corrugated board" },
      { label: "Corrugation Hydraulic Reel Stand (KG-HRS)", value: "Hydraulic reel stand for semi-automatic corrugation plants" },
      { label: "4-Bar Rotary Heavy Duty Machine (KG-4BR)", value: "Four-bar rotary corrugation unit for heavy duty output" },
      { label: "Slotting Machine (KG-SL)", value: "Standalone slotting machine for shorter runs and rework" },
      { label: "Box Stitching Machine (KG-BSM)", value: "Pedestal box stitching machine for single and double-wall cartons" },
      { label: "Die-Punching Heavy Duty Machine (KG-DPH)", value: "Heavy duty die punching press for cut-and-crease work" },
      { label: "Pasting Machine \u2014 Heavy Duty (KG-PST/H)", value: "Long-bed pasting machine for wide sheet lamination" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/carton-plant-machinery-23-1.jpeg", "/images/catalogue/carton-plant-machinery-23-2.jpeg", "/images/catalogue/carton-plant-machinery-23-3.jpeg", "/images/catalogue/carton-plant-machinery-23-4.jpeg", "/images/catalogue/carton-plant-machinery-23-5.jpeg", "/images/catalogue/carton-plant-machinery-23-6.jpeg", "/images/catalogue/carton-plant-machinery-23-7.jpeg", "/images/catalogue/carton-plant-machinery-23-8.jpeg", "/images/catalogue/carton-plant-machinery-23-9.jpeg", "/images/catalogue/carton-plant-machinery-23-10.jpeg", "/images/catalogue/carton-plant-machinery-23-11.jpeg", "/images/catalogue/carton-plant-machinery-23-12.jpeg"],
      previews: ["/images/catalogue/carton-plant-machinery-23-1.jpeg", "/images/catalogue/carton-plant-machinery-23-2.jpeg", "/images/catalogue/carton-plant-machinery-23-3.jpeg", "/images/catalogue/carton-plant-machinery-23-4.jpeg", "/images/catalogue/carton-plant-machinery-23-5.jpeg", "/images/catalogue/carton-plant-machinery-23-6.jpeg", "/images/catalogue/carton-plant-machinery-23-7.jpeg", "/images/catalogue/carton-plant-machinery-23-8.jpeg", "/images/catalogue/carton-plant-machinery-23-9.jpeg", "/images/catalogue/carton-plant-machinery-23-10.jpeg", "/images/catalogue/carton-plant-machinery-23-11.jpeg", "/images/catalogue/carton-plant-machinery-23-12.jpeg"],
    },
  },
  {
    id: 24,
    title: "Corrugated Machinery Spares",
    category: "Packaging & Corrugation Machinery",
    subCategory: "Spare Parts",
    description: "Fast-moving wear parts and consumables for corrugation and carton-converting machinery, held for short-lead replacement. Parts can be supplied to sample, drawing or machine serial number. Volume 1 of 4 \u2014 includes brake bands, corrugated rollers, printing inks, pumps and more.",
    specifications: [
      { label: "CS-001", value: "Brake Band & Shoe Segments" },
      { label: "CS-002", value: "Slitting & Creasing Discs" },
      { label: "CS-003", value: "Bearing & Wear Rings" },
      { label: "CS-004", value: "Corrugated Roller" },
      { label: "CS-005", value: "Printing Ink \u2014 Process Colours" },
      { label: "CS-006", value: "Gear Pump Assembly" },
      { label: "CS-007", value: "Motor Head Assembly" },
      { label: "CS-008", value: "Printing Ink \u2014 Extended Range" },
      { label: "CS-009", value: "Pneumatic Cylinder Assembly" },
      { label: "CS-010", value: "Diaphragm Pump Set" },
      { label: "CS-011", value: "Board Guide Brackets" },
      { label: "CS-012", value: "Electric & Pneumatic Wire Cutters" },
      { label: "CS-013", value: "Green Conveyor Belt" },
      { label: "CS-014", value: "Splice Tape & Joint Plates" },
      { label: "CS-015", value: "Thin Blade Set" },
      { label: "CS-016", value: "Glue Head \u2014 Hot Melt" },
      { label: "CS-017", value: "Rotary Joint" },
      { label: "CS-018", value: "Hand Pull Pump" },
      { label: "CS-019", value: "Stitching Wire Coil \u2014 Copper Coated" },
      { label: "CS-020", value: "Feeding Wheel \u2014 Polyurethane" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/corrugated-machinery-spares-24-1.jpeg", "/images/catalogue/corrugated-machinery-spares-24-2.jpeg", "/images/catalogue/corrugated-machinery-spares-24-3.jpeg", "/images/catalogue/corrugated-machinery-spares-24-4.jpeg", "/images/catalogue/corrugated-machinery-spares-24-5.jpeg", "/images/catalogue/corrugated-machinery-spares-24-6.jpeg", "/images/catalogue/corrugated-machinery-spares-24-7.jpeg", "/images/catalogue/corrugated-machinery-spares-24-8.jpeg", "/images/catalogue/corrugated-machinery-spares-24-9.jpeg", "/images/catalogue/corrugated-machinery-spares-24-10.jpeg", "/images/catalogue/corrugated-machinery-spares-24-11.jpeg", "/images/catalogue/corrugated-machinery-spares-24-12.jpeg", "/images/catalogue/corrugated-machinery-spares-24-13.jpeg", "/images/catalogue/corrugated-machinery-spares-24-14.jpeg", "/images/catalogue/corrugated-machinery-spares-24-15.jpeg", "/images/catalogue/corrugated-machinery-spares-24-16.jpeg", "/images/catalogue/corrugated-machinery-spares-24-17.jpeg", "/images/catalogue/corrugated-machinery-spares-24-18.jpeg", "/images/catalogue/corrugated-machinery-spares-24-19.jpeg", "/images/catalogue/corrugated-machinery-spares-24-20.jpeg"],
      previews: ["/images/catalogue/corrugated-machinery-spares-24-1.jpeg", "/images/catalogue/corrugated-machinery-spares-24-2.jpeg", "/images/catalogue/corrugated-machinery-spares-24-3.jpeg", "/images/catalogue/corrugated-machinery-spares-24-4.jpeg", "/images/catalogue/corrugated-machinery-spares-24-5.jpeg", "/images/catalogue/corrugated-machinery-spares-24-6.jpeg", "/images/catalogue/corrugated-machinery-spares-24-7.jpeg", "/images/catalogue/corrugated-machinery-spares-24-8.jpeg", "/images/catalogue/corrugated-machinery-spares-24-9.jpeg", "/images/catalogue/corrugated-machinery-spares-24-10.jpeg", "/images/catalogue/corrugated-machinery-spares-24-11.jpeg", "/images/catalogue/corrugated-machinery-spares-24-12.jpeg", "/images/catalogue/corrugated-machinery-spares-24-13.jpeg", "/images/catalogue/corrugated-machinery-spares-24-14.jpeg", "/images/catalogue/corrugated-machinery-spares-24-15.jpeg", "/images/catalogue/corrugated-machinery-spares-24-16.jpeg", "/images/catalogue/corrugated-machinery-spares-24-17.jpeg", "/images/catalogue/corrugated-machinery-spares-24-18.jpeg", "/images/catalogue/corrugated-machinery-spares-24-19.jpeg", "/images/catalogue/corrugated-machinery-spares-24-20.jpeg"],
    },
  },
  {
    id: 25,
    title: "Corrugated Machinery Spares \u2014 Volume 2",
    category: "Packaging & Corrugation Machinery",
    subCategory: "Spare Parts",
    description: "Fast-moving wear parts and consumables for corrugation and carton-converting machinery, held for short-lead replacement. Volume 2 of 4 \u2014 includes timing wheels, gears, cutter blades and pumps.",
    specifications: [
      { label: "CS-021", value: "Timing Wheel Set" },
      { label: "CS-022", value: "Aluminium Hanging Groove" },
      { label: "CS-023", value: "Cleaning Brush & Blade Set" },
      { label: "CS-024", value: "Corrugation Screen Plate" },
      { label: "CS-025", value: "Digital Counters & Controllers" },
      { label: "CS-026", value: "Alloy Bottom Die" },
      { label: "CS-027", value: "Idle Gear" },
      { label: "CS-028", value: "Transmission Gear Set" },
      { label: "CS-029", value: "Suction Belt \u2014 Perforated" },
      { label: "CS-030", value: "Blade Seat Strips" },
      { label: "CS-031", value: "Aluminium Baffle" },
      { label: "CS-032", value: "Stainless Steel Baffle" },
      { label: "CS-033", value: "Feeding Wheels \u2014 Assorted" },
      { label: "CS-034", value: "Rubber Pad" },
      { label: "CS-035", value: "Fork Blade Set" },
      { label: "CS-036", value: "Angle Cutter Blades" },
      { label: "CS-037", value: "Wire Bending Head" },
      { label: "CS-038", value: "Gear Oil Pump" },
      { label: "CS-039", value: "Ink Pump" },
      { label: "CS-040", value: "Oil-Bearing Accessory" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/corrugated-machinery-spares-volume-2-25-1.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-2-25-2.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-2-25-3.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-2-25-4.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-2-25-5.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-2-25-6.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-2-25-7.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-2-25-8.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-2-25-9.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-2-25-10.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-2-25-11.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-2-25-12.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-2-25-13.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-2-25-14.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-2-25-15.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-2-25-16.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-2-25-17.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-2-25-18.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-2-25-19.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-2-25-20.jpeg"],
      previews: ["/images/catalogue/corrugated-machinery-spares-volume-2-25-1.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-2-25-2.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-2-25-3.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-2-25-4.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-2-25-5.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-2-25-6.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-2-25-7.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-2-25-8.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-2-25-9.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-2-25-10.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-2-25-11.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-2-25-12.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-2-25-13.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-2-25-14.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-2-25-15.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-2-25-16.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-2-25-17.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-2-25-18.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-2-25-19.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-2-25-20.jpeg"],
    },
  },
  {
    id: 26,
    title: "Corrugated Machinery Spares \u2014 Volume 3",
    category: "Packaging & Corrugation Machinery",
    subCategory: "Spare Parts",
    description: "Fast-moving wear parts and consumables for corrugation and carton-converting machinery, held for short-lead replacement. Volume 3 of 4 \u2014 includes drive components, seal discs and pneumatic fittings.",
    specifications: [
      { label: "CS-041", value: "Phase Adjuster Drive" },
      { label: "CS-042", value: "Drive Belt" },
      { label: "CS-043", value: "Bottom Die Fixed Tray" },
      { label: "CS-044", value: "Ceramic Wear Plates" },
      { label: "CS-045", value: "Rotary Joint Soft Pipe" },
      { label: "CS-046", value: "Waste Remove Belt" },
      { label: "CS-047", value: "Glue Spray Manifold" },
      { label: "CS-048", value: "Pump Pad \u2014 Perforated" },
      { label: "CS-049", value: "Knife Comb" },
      { label: "CS-050", value: "Paper Guide Fork" },
      { label: "CS-051", value: "Transmission Cross Shaft" },
      { label: "CS-052", value: "Pneumatic Tubing \u2014 PU" },
      { label: "CS-053", value: "Bending Guide Rail" },
      { label: "CS-054", value: "Carbon Rings & Seal Discs" },
      { label: "CS-055", value: "Sun Wheel Assembly" },
      { label: "CS-056", value: "Air Bag \u2014 Pressure" },
      { label: "CS-057", value: "Handwheels & Knobs" },
      { label: "CS-058", value: "Vacuum Manifold Block" },
      { label: "CS-059", value: "Electromagnetic Clutch" },
      { label: "CS-060", value: "Vacuum Suction Box" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/corrugated-machinery-spares-volume-3-26-1.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-3-26-2.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-3-26-3.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-3-26-4.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-3-26-5.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-3-26-6.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-3-26-7.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-3-26-8.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-3-26-9.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-3-26-10.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-3-26-11.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-3-26-12.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-3-26-13.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-3-26-14.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-3-26-15.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-3-26-16.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-3-26-17.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-3-26-18.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-3-26-19.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-3-26-20.jpeg"],
      previews: ["/images/catalogue/corrugated-machinery-spares-volume-3-26-1.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-3-26-2.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-3-26-3.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-3-26-4.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-3-26-5.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-3-26-6.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-3-26-7.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-3-26-8.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-3-26-9.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-3-26-10.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-3-26-11.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-3-26-12.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-3-26-13.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-3-26-14.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-3-26-15.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-3-26-16.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-3-26-17.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-3-26-18.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-3-26-19.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-3-26-20.jpeg"],
    },
  },
  {
    id: 27,
    title: "Corrugated Machinery Spares \u2014 Volume 4",
    category: "Packaging & Corrugation Machinery",
    subCategory: "Spare Parts",
    description: "Fast-moving wear parts and consumables for corrugation and carton-converting machinery, held for short-lead replacement. Volume 4 of 4 \u2014 includes blades, hoses, gearboxes and bearing brackets.",
    specifications: [
      { label: "CS-061", value: "Paper Feeding Wheel Set" },
      { label: "CS-062", value: "Die Cutting Blades" },
      { label: "CS-063", value: "Link Rods & Levers" },
      { label: "CS-064", value: "Bearing Roller Brackets" },
      { label: "CS-065", value: "Pneumatic Tubing Reels" },
      { label: "CS-066", value: "Spiral & Coil Air Hose" },
      { label: "CS-067", value: "Flexible Suction Hose" },
      { label: "CS-068", value: "Bushes, Bearings & Fittings" },
      { label: "CS-069", value: "Curved Slotting Blades" },
      { label: "CS-070", value: "Creasing Blades" },
      { label: "CS-071", value: "Slideway Rail" },
      { label: "CS-072", value: "Vacuum Rail \u2014 Perforated" },
      { label: "CS-073", value: "Bellow Covers" },
      { label: "CS-074", value: "Wire Feeder Head" },
      { label: "CS-075", value: "Nozzle Assemblies" },
      { label: "CS-076", value: "Glue Head Assembly" },
      { label: "CS-077", value: "Worm Reduction Gearbox" },
      { label: "CS-078", value: "Timing Belts \u2014 Assorted" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/corrugated-machinery-spares-volume-4-27-1.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-4-27-2.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-4-27-3.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-4-27-4.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-4-27-5.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-4-27-6.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-4-27-7.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-4-27-8.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-4-27-9.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-4-27-10.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-4-27-11.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-4-27-12.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-4-27-13.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-4-27-14.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-4-27-15.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-4-27-16.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-4-27-17.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-4-27-18.jpeg"],
      previews: ["/images/catalogue/corrugated-machinery-spares-volume-4-27-1.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-4-27-2.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-4-27-3.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-4-27-4.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-4-27-5.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-4-27-6.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-4-27-7.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-4-27-8.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-4-27-9.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-4-27-10.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-4-27-11.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-4-27-12.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-4-27-13.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-4-27-14.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-4-27-15.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-4-27-16.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-4-27-17.jpeg", "/images/catalogue/corrugated-machinery-spares-volume-4-27-18.jpeg"],
    },
  },
  {
    id: 28,
    title: "Rubber Bellow Seal",
    category: "Sealing & Fluid Handling",
    subCategory: "Mechanical Seals",
    description: "Water pumps duty mechanical seal. Face and elastomer combinations are selected to the medium, pressure and temperature of the duty.",
    specifications: [
      { label: "Face materials", value: "Silicon Carbide, Carbon, Tungsten Carbide, Ceramic" },
      { label: "Metal parts", value: "AISI SS 316, AISI SS 304" },
      { label: "Seal elastomer", value: "Viton, EPDM, NBR" },
      { label: "Applications", value: "Water pumps, submersible pumps, sewage pumps" },
      { label: "Shaft diameter d1", value: "10 \u2013 100 mm" },
      { label: "Pressure p", value: "10 bar (max)" },
      { label: "Temperature", value: "\u221220 \u2026 +180 \u00b0C" },
      { label: "Speed", value: "3000 rpm" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/rubber-bellow-seal-28-1.jpeg"],
      previews: ["/images/catalogue/rubber-bellow-seal-28-1.jpeg"],
    },
  },
  {
    id: 29,
    title: "Multi Spring Seal",
    category: "Sealing & Fluid Handling",
    subCategory: "Mechanical Seals",
    description: "Light hydrocarbons duty mechanical seal. Face and elastomer combinations are selected to the medium, pressure and temperature of the duty.",
    specifications: [
      { label: "Face materials", value: "Carbon, Ceramic, Silicon Carbide, Tungsten Carbide" },
      { label: "Metal parts", value: "AISI SS 316, AISI SS 304, Hastelloy-C, Alloy-20" },
      { label: "Seal elastomer", value: "Viton, EPDM, Silicon, Aflas, PTFE, GFT, Kalrez, FEP, TTV" },
      { label: "Applications", value: "Light hydrocarbons, corrosive services, acids and alkalies, petrochemicals" },
      { label: "Shaft diameter d1", value: "20 \u2013 100 mm" },
      { label: "Pressure p", value: "20 bar (max)" },
      { label: "Temperature", value: "up to +180 \u00b0C" },
      { label: "Speed", value: "3000 rpm" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/multi-spring-seal-29-1.jpeg"],
      previews: ["/images/catalogue/multi-spring-seal-29-1.jpeg"],
    },
  },
  {
    id: 30,
    title: "Reverse Balance Multi Spring Seal",
    category: "Sealing & Fluid Handling",
    subCategory: "Mechanical Seals",
    description: "Light hydrocarbons duty mechanical seal. Face and elastomer combinations are selected to the medium, pressure and temperature of the duty.",
    specifications: [
      { label: "Face materials", value: "Carbon, Ceramic, Silicon Carbide, Tungsten Carbide" },
      { label: "Metal parts", value: "AISI SS 316, AISI SS 304, Hastelloy-C, Alloy-20" },
      { label: "Seal elastomer", value: "Viton, EPDM, TTV, FEP and FKM" },
      { label: "Applications", value: "Light hydrocarbons, corrosive services, acids and alkalies, petrochemicals" },
      { label: "Shaft diameter d1", value: "12 \u2013 70 mm" },
      { label: "Pressure p", value: "08 bar (max)" },
      { label: "Temperature", value: "up to +120 \u00b0C" },
      { label: "Speed", value: "3000 rpm" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/reverse-balance-multi-spring-seal-30-1.jpeg"],
      previews: ["/images/catalogue/reverse-balance-multi-spring-seal-30-1.jpeg"],
    },
  },
  {
    id: 31,
    title: "Wave Spring Seal",
    category: "Sealing & Fluid Handling",
    subCategory: "Mechanical Seals",
    description: "Slurry pumps duty mechanical seal. Face and elastomer combinations are selected to the medium, pressure and temperature of the duty.",
    specifications: [
      { label: "Face materials", value: "Carbon, Ceramic, Silicon Carbide, Tungsten Carbide" },
      { label: "Metal parts", value: "AISI SS 316, AISI SS 304, Hastelloy-C, Alloy-20" },
      { label: "Seal elastomer", value: "Viton, EPDM, TTV, FEP and FKM" },
      { label: "Applications", value: "Slurry pumps, pulp and paper, sludge and syrup pumps, chemical, petrochemical and refinery" },
      { label: "Shaft diameter d1", value: "12 \u2013 70 mm" },
      { label: "Pressure p", value: "08 bar (max)" },
      { label: "Temperature", value: "up to +120 \u00b0C" },
      { label: "Speed", value: "3000 rpm" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/wave-spring-seal-31-1.jpeg"],
      previews: ["/images/catalogue/wave-spring-seal-31-1.jpeg"],
    },
  },
  {
    id: 32,
    title: "Single Coil Spring Seal",
    category: "Sealing & Fluid Handling",
    subCategory: "Mechanical Seals",
    description: "Crystallizing slurry duty mechanical seal. Face and elastomer combinations are selected to the medium, pressure and temperature of the duty.",
    specifications: [
      { label: "Face materials", value: "Carbon, Ceramic, Tungsten Carbide, Silicon Carbide, Lecrolloy" },
      { label: "Metal parts", value: "AISI SS 316, AISI SS 304, Hastelloy-C, Alloy-20" },
      { label: "Seal elastomer", value: "Viton, EPDM, Silicon, Aflas, GFT, Kalrez, FEP, TTV, PTFE" },
      { label: "Applications", value: "Crystallizing slurry, suspended solids slurry, saturated and general chemical slurry" },
      { label: "Shaft diameter d1", value: "12 \u2013 100 mm" },
      { label: "Pressure p", value: "12 bar (max)" },
      { label: "Temperature", value: "\u221220 \u2026 +180 \u00b0C" },
      { label: "Speed", value: "3000 rpm" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/single-coil-spring-seal-32-1.jpeg"],
      previews: ["/images/catalogue/single-coil-spring-seal-32-1.jpeg"],
    },
  },
  {
    id: 33,
    title: "Conical Coil Single Spring Seal",
    category: "Sealing & Fluid Handling",
    subCategory: "Mechanical Seals",
    description: "Water pumps duty mechanical seal. Face and elastomer combinations are selected to the medium, pressure and temperature of the duty.",
    specifications: [
      { label: "Face materials", value: "Carbon, Ceramic, Tungsten Carbide, Silicon Carbide, Lecrolloy" },
      { label: "Metal parts", value: "AISI SS 316, AISI SS 304, Hastelloy-C, Alloy-20" },
      { label: "Seal elastomer", value: "Viton, EPDM, Silicon, Aflas, PTFE, GFT, Kalrez, FEP, TTV" },
      { label: "Applications", value: "Water pumps, circulation pumps for central heating, chemical process pumps, sewage and submersible pumps" },
      { label: "Shaft diameter d1", value: "12 \u2013 90 mm" },
      { label: "Pressure p", value: "08 bar (max)" },
      { label: "Temperature", value: "\u221220 \u2026 +180 \u00b0C" },
      { label: "Speed", value: "3000 rpm" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/conical-coil-single-spring-seal-33-1.jpeg"],
      previews: ["/images/catalogue/conical-coil-single-spring-seal-33-1.jpeg"],
    },
  },
  {
    id: 34,
    title: "PTFE Bellow Seal",
    category: "Sealing & Fluid Handling",
    subCategory: "Mechanical Seals",
    description: "Extremely corrosive services duty mechanical seal. Face and elastomer combinations are selected to the medium, pressure and temperature of the duty.",
    specifications: [
      { label: "Face materials", value: "GFT, Ceramic, Silicon Carbide, CFT" },
      { label: "Metal parts", value: "AISI SS 316, AISI SS 304, Hastelloy-C, Alloy-20" },
      { label: "Seal elastomer", value: "PTFE and GFT" },
      { label: "Applications", value: "Extremely corrosive services" },
      { label: "Shaft diameter d1", value: "18 \u2013 100 mm" },
      { label: "Pressure p", value: "06 bar (max)" },
      { label: "Temperature", value: "\u221230 \u2026 +120 \u00b0C" },
      { label: "Speed", value: "3000 rpm" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/ptfe-bellow-seal-34-1.jpeg"],
      previews: ["/images/catalogue/ptfe-bellow-seal-34-1.jpeg"],
    },
  },
  {
    id: 35,
    title: "Metal Bellow Seal",
    category: "Sealing & Fluid Handling",
    subCategory: "Mechanical Seals",
    description: "Chemicals duty mechanical seal. Face and elastomer combinations are selected to the medium, pressure and temperature of the duty.",
    specifications: [
      { label: "Face materials", value: "Carbon, Silicon Carbide, Tungsten Carbide" },
      { label: "Metal parts", value: "AISI SS 316, AISI SS 304, Carpenter 42" },
      { label: "Seal elastomer", value: "Flexible graphite, Viton, CFT" },
      { label: "Applications", value: "Chemicals, petrochemical, refinery, corrosive chemical, extreme hot media" },
      { label: "Shaft diameter d1", value: "25 \u2013 100 mm" },
      { label: "Pressure p", value: "25 bar (max)" },
      { label: "Temperature", value: "\u221270 \u2026 +350 \u00b0C" },
      { label: "Speed", value: "3000 rpm" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/metal-bellow-seal-35-1.jpeg"],
      previews: ["/images/catalogue/metal-bellow-seal-35-1.jpeg"],
    },
  },
  {
    id: 36,
    title: "Single Cartridge Seal",
    category: "Sealing & Fluid Handling",
    subCategory: "Mechanical Seals",
    description: "Slurry pumps duty mechanical seal. Face and elastomer combinations are selected to the medium, pressure and temperature of the duty.",
    specifications: [
      { label: "Face materials", value: "Carbon, Tungsten Carbide, Silicon Carbide" },
      { label: "Metal parts", value: "AISI SS 316, AISI SS 304, Carpenter 42" },
      { label: "Seal elastomer", value: "Viton, EPDM, Silicon, Aflas, PTFE, GFT, Kalrez, FEP, TTV" },
      { label: "Applications", value: "Slurry pumps, pulp and paper, sludge and syrup pumps, chemical, petrochemical, refinery, light hydrocarbons" },
      { label: "Shaft diameter d1", value: "18 \u2013 100 mm" },
      { label: "Pressure p", value: "5 \u2013 35 bar (max)" },
      { label: "Temperature", value: "\u221220 \u2026 +260 \u00b0C" },
      { label: "Speed", value: "3000 rpm" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/single-cartridge-seal-36-1.jpeg"],
      previews: ["/images/catalogue/single-cartridge-seal-36-1.jpeg"],
    },
  },
  {
    id: 37,
    title: "Dual Cartridge Seal",
    category: "Sealing & Fluid Handling",
    subCategory: "Mechanical Seals",
    description: "Slurry pumps duty mechanical seal. Face and elastomer combinations are selected to the medium, pressure and temperature of the duty.",
    specifications: [
      { label: "Face materials", value: "Carbon, Silicon Carbide, Tungsten Carbide, Lecrolloy" },
      { label: "Metal parts", value: "AISI SS 316, AISI SS 304, Hastelloy-C, Alloy-20" },
      { label: "Seal elastomer", value: "Viton, EPDM, Silicon, Aflas, PTFE, GFT, Kalrez, FEP, TTV" },
      { label: "Applications", value: "Slurry pumps, pulp and paper, sludge and syrup pumps, chemical, petrochemical and refinery" },
      { label: "Shaft diameter d1", value: "18 \u2013 100 mm" },
      { label: "Pressure p", value: "05 \u2013 35 bar (max)" },
      { label: "Temperature", value: "\u221220 \u2026 260 \u00b0C" },
      { label: "Speed", value: "3000 rpm" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/dual-cartridge-seal-37-1.jpeg"],
      previews: ["/images/catalogue/dual-cartridge-seal-37-1.jpeg"],
    },
  },
  {
    id: 38,
    title: "Single Agitator Seal",
    category: "Sealing & Fluid Handling",
    subCategory: "Mechanical Seals",
    description: "Corrosive chemical duty mechanical seal. Face and elastomer combinations are selected to the medium, pressure and temperature of the duty.",
    specifications: [
      { label: "Face materials", value: "Carbon, Silicon Carbide, Tungsten Carbide, Ceramic" },
      { label: "Metal parts", value: "AISI SS 316, AISI SS 304, Hastelloy-C, Alloy-20" },
      { label: "Seal elastomer", value: "Viton, EPDM, Silicon, Aflas, PTFE, GFT, Kalrez, FEP, TTV" },
      { label: "Applications", value: "Corrosive chemical, general light chemical, food products, pharmaceutical products" },
      { label: "Shaft diameter d1", value: "25 \u2013 200 mm" },
      { label: "Pressure p", value: "vacuum \u2026 30 bar (max)" },
      { label: "Temperature", value: "\u221230 \u2026 +260 \u00b0C" },
      { label: "Speed", value: "3000 rpm" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/single-agitator-seal-38-1.jpeg"],
      previews: ["/images/catalogue/single-agitator-seal-38-1.jpeg"],
    },
  },
  {
    id: 39,
    title: "Dual Agitator Seal",
    category: "Sealing & Fluid Handling",
    subCategory: "Mechanical Seals",
    description: "General chemicals and vapours duty mechanical seal. Face and elastomer combinations are selected to the medium, pressure and temperature of the duty.",
    specifications: [
      { label: "Face materials", value: "Carbon, Silicon Carbide, Tungsten Carbide, Lecrolloy, Ceramic" },
      { label: "Metal parts", value: "AISI SS 316, AISI SS 304, Hastelloy-C, Alloy-20" },
      { label: "Seal elastomer", value: "Viton, EPDM, Silicon, Aflas, PTFE, GFT, Kalrez, FEP, TTV" },
      { label: "Applications", value: "General chemicals and vapours, petrochemicals, light hydrocarbons, pharmaceutical and paper industries" },
      { label: "Shaft diameter d1", value: "25 \u2013 200 mm" },
      { label: "Pressure p", value: "vacuum \u2026 30 bar (max)" },
      { label: "Temperature", value: "\u221230 \u2026 +260 \u00b0C" },
      { label: "Speed", value: "3000 rpm" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/dual-agitator-seal-39-1.jpeg"],
      previews: ["/images/catalogue/dual-agitator-seal-39-1.jpeg"],
    },
  },
  {
    id: 40,
    title: "Dry Running Seal",
    category: "Sealing & Fluid Handling",
    subCategory: "Mechanical Seals",
    description: "Corrosive chemicals duty mechanical seal. Face and elastomer combinations are selected to the medium, pressure and temperature of the duty.",
    specifications: [
      { label: "Face materials", value: "Carbon, Silicon Carbide, Tungsten Carbide, Ceramic" },
      { label: "Metal parts", value: "AISI SS 316, AISI SS 304, MS" },
      { label: "Seal elastomer", value: "Viton, EPDM, Silicon, Aflas, PTFE, GFT, Kalrez, FEP, TTV" },
      { label: "Applications", value: "Corrosive chemicals, general light chemicals, food products" },
      { label: "Shaft diameter d1", value: "15 \u2013 150 mm" },
      { label: "Pressure p", value: "08 bar (max)" },
      { label: "Temperature", value: "\u221230 \u2026 150 \u00b0C" },
      { label: "Speed", value: "3000 rpm" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/dry-running-seal-40-1.jpeg"],
      previews: ["/images/catalogue/dry-running-seal-40-1.jpeg"],
    },
  },
  {
    id: 41,
    title: "Water Pump Seals \u2014 All Types",
    category: "Sealing & Fluid Handling",
    subCategory: "Mechanical Seals",
    description: "Domestic duty mechanical seal. Face and elastomer combinations are selected to the medium, pressure and temperature of the duty.",
    specifications: [
      { label: "Face materials", value: "Carbon, Silicon Carbide, Tungsten Carbide, Stelite" },
      { label: "Metal parts", value: "AISI SS 316, AISI SS 304, MS" },
      { label: "Seal elastomer", value: "Viton, EPDM, Silicon, NBR" },
      { label: "Applications", value: "Domestic, agricultural and industrial water pumping" },
      { label: "Size", value: "12 mm to 85 mm" },
      { label: "Pressure", value: "as per customer criteria" },
      { label: "Temperature", value: "as per customer criteria" },
      { label: "Speed", value: "as per customer criteria" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/water-pump-seals-all-types-41-1.jpeg"],
      previews: ["/images/catalogue/water-pump-seals-all-types-41-1.jpeg"],
    },
  },
  {
    id: 42,
    title: "Rotary Joint for Water Application",
    category: "Sealing & Fluid Handling",
    subCategory: "Rotary Unions",
    description: "Rotary union for transferring water into rotating drums, rolls and cylinders \u2014 self-supported and externally supported mounting, with and without internal syphon pipe.",
    specifications: [
      { label: "Face materials", value: "Carbon, Silicon Carbide, Tungsten Carbide, Stelite" },
      { label: "Metal parts", value: "SS 316, SS 304, Brass" },
      { label: "Seal elastomer", value: "Viton, Silicon, TTV, PTFE" },
      { label: "Size", value: "3/8\" to 6.0\"" },
      { label: "Pressure", value: "15 bar" },
      { label: "Temperature", value: "150 \u00b0C" },
      { label: "Speed", value: "3500 rpm" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/rotary-joint-for-water-application-42-1.jpeg"],
      previews: ["/images/catalogue/rotary-joint-for-water-application-42-1.jpeg"],
    },
  },
  {
    id: 43,
    title: "Rotary Joint for Air Application",
    category: "Sealing & Fluid Handling",
    subCategory: "Rotary Unions",
    description: "Rotary union for transferring compressed air or vacuum into rotating drums, rolls and cylinders.",
    specifications: [
      { label: "Face materials", value: "Carbon, Silicon Carbide, Tungsten Carbide, Stelite" },
      { label: "Metal parts", value: "Aluminium" },
      { label: "Seal elastomer", value: "Viton, PTFE" },
      { label: "Size", value: "3/8\" to 6.0\"" },
      { label: "Pressure", value: "10 bar air, 0.07 bar to 7 kPa vacuum" },
      { label: "Temperature", value: "150 \u00b0C" },
      { label: "Speed", value: "2800 rpm" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/rotary-joint-for-air-application-43-1.jpeg"],
      previews: ["/images/catalogue/rotary-joint-for-air-application-43-1.jpeg"],
    },
  },
  {
    id: 44,
    title: "Hydraulic Rotary Joint",
    category: "Sealing & Fluid Handling",
    subCategory: "Rotary Unions",
    description: "Rotary union for transferring hydraulic oil into rotating drums, rolls and cylinders at high working pressure.",
    specifications: [
      { label: "Face materials", value: "Carbon, Silicon Carbide" },
      { label: "Metal parts", value: "SS 316, SS 304, Brass, Gun Metal" },
      { label: "Seal elastomer", value: "Viton, PTFE" },
      { label: "Size", value: "3/8\" to 6.0\"" },
      { label: "Pressure", value: "400 bar" },
      { label: "Temperature", value: "150 \u00b0C" },
      { label: "Speed", value: "1500 rpm" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/hydraulic-rotary-joint-44-1.jpeg"],
      previews: ["/images/catalogue/hydraulic-rotary-joint-44-1.jpeg"],
    },
  },
  {
    id: 45,
    title: "Rotary Joint for Hot Oil & Thermic Fluid",
    category: "Sealing & Fluid Handling",
    subCategory: "Rotary Unions",
    description: "Rotary union for thermic fluid heating circuits on rotating drums and cylinders, sealed with grafoil or asbestos gasket for high temperature service.",
    specifications: [
      { label: "Face materials", value: "Antimony Carbon" },
      { label: "Metal parts", value: "MS, SS 304" },
      { label: "Seal elastomer", value: "Grafoil gasket, asbestos gasket" },
      { label: "Size", value: "0.5\" to 6.0\"" },
      { label: "Pressure", value: "07 bar" },
      { label: "Temperature", value: "350 \u00b0C" },
      { label: "Speed", value: "750 rpm" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/rotary-joint-for-hot-oil-thermic-fluid-45-1.jpeg"],
      previews: ["/images/catalogue/rotary-joint-for-hot-oil-thermic-fluid-45-1.jpeg"],
    },
  },
  {
    id: 46,
    title: "Thermosyphon Vessel",
    category: "Sealing & Fluid Handling",
    subCategory: "Rotary Unions",
    description: "Thermosyphon vessel for thermic fluid rotary joint circuits, in carbon steel or stainless shell with matched cooling coil.",
    specifications: [
      { label: "Shell material", value: "Carbon steel / SS 304 / SS 316" },
      { label: "Cooling coil", value: "MS / SS 304 / SS 316" },
      { label: "Pressure limit \u2014 20 series", value: "20 bar" },
      { label: "Pressure limit \u2014 40 series", value: "40 bar" },
      { label: "Temperature (max)", value: "200 \u00b0C" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/thermosyphon-vessel-46-1.jpeg"],
      previews: ["/images/catalogue/thermosyphon-vessel-46-1.jpeg"],
    },
  },
  {
    id: 47,
    title: "Pump Spares",
    category: "Sealing & Fluid Handling",
    subCategory: "Pump Spares",
    description: "Replacement wet-end and bearing-end components for centrifugal process pumps, manufactured to sample or drawing in cast iron, carbon steel, stainless and duplex grades. Components are manufactured to sample or drawing; please quote the pump make, model, serial number and part reference when enquiring \u2014 where no drawing exists the worn part can be reverse-engineered.",
    specifications: [
      { label: "Impeller", value: "Closed, semi-open and open impellers in CI, CS, SS 316 and duplex grades" },
      { label: "Pump Shaft", value: "Ground and polished shafts to original dimensions and runout limits" },
      { label: "Casing", value: "Volute casings and covers, machined and pressure tested" },
      { label: "Shaft Sleeve", value: "Hardened and coated sleeves for extended seal-face life" },
      { label: "Stuffing Box", value: "Stuffing boxes and seal chambers for gland or cartridge conversion" },
      { label: "Bearing Housing", value: "Bearing housings with oil or grease lubrication arrangement" },
      { label: "Wear Ring", value: "Casing and impeller wear rings machined to running clearance" },
      { label: "Bearing Cover", value: "Bearing covers, end covers and seal housings" },
      { label: "Pump ranges served", value: "Centrifugal process, end suction, split case, vertical sump, slurry, gear, screw, vacuum, submersible and monoblock pumps" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/pump-spares-47-1.jpeg", "/images/catalogue/pump-spares-47-2.jpeg", "/images/catalogue/pump-spares-47-3.jpeg", "/images/catalogue/pump-spares-47-4.jpeg", "/images/catalogue/pump-spares-47-5.jpeg", "/images/catalogue/pump-spares-47-6.jpeg", "/images/catalogue/pump-spares-47-7.jpeg", "/images/catalogue/pump-spares-47-8.jpeg"],
      previews: ["/images/catalogue/pump-spares-47-1.jpeg", "/images/catalogue/pump-spares-47-2.jpeg", "/images/catalogue/pump-spares-47-3.jpeg", "/images/catalogue/pump-spares-47-4.jpeg", "/images/catalogue/pump-spares-47-5.jpeg", "/images/catalogue/pump-spares-47-6.jpeg", "/images/catalogue/pump-spares-47-7.jpeg", "/images/catalogue/pump-spares-47-8.jpeg"],
    },
  },
  {
    id: 48,
    title: "Rubber, Silicone & PTFE Products",
    category: "Sealing & Fluid Handling",
    subCategory: "Elastomers & Polymers",
    description: "Moulded and extruded elastomer components for process, pharmaceutical and food plant \u2014 gaskets, diaphragms, bellows, hoses, sheeting and machined PTFE.",
    specifications: [
      { label: "FBD Gasket", value: "Flanged bellow duct gasket" },
      { label: "Silicon Sponges & Strips", value: "Extruded profiles and sponge strip" },
      { label: "Rubber Diaphragms", value: "Moulded process diaphragms" },
      { label: "Rubber Expansion Bellow", value: "Piping expansion joints" },
      { label: "Tri Clamp Gasket (TC Gasket)", value: "Hygienic tri-clamp gaskets" },
      { label: "O-Rings \u2014 All Types", value: "Standard and custom sizes" },
      { label: "Silicon Bellow", value: "Flexible silicone ducting" },
      { label: "Silicon Transparent Tubes", value: "Food and pharma grade tubing" },
      { label: "Braided Hose", value: "Reinforced braided hose" },
      { label: "Thunder Hose", value: "Heavy-duty industrial hose" },
      { label: "PHE Gaskets & Plates", value: "Plate heat exchanger gaskets" },
      { label: "Rubber Sheet", value: "Sheeting for gaskets and lining" },
      { label: "Multimill Middle Gasket", value: "Pharma multimill gasket" },
      { label: "Butterfly Gaskets", value: "Valve seating gaskets" },
      { label: "Teflon Hose", value: "PTFE-lined hose" },
      { label: "PTFE (Teflon) Products", value: "Machined PTFE components" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/rubber-silicone-ptfe-products-48-1.jpeg", "/images/catalogue/rubber-silicone-ptfe-products-48-2.jpeg", "/images/catalogue/rubber-silicone-ptfe-products-48-3.jpeg", "/images/catalogue/rubber-silicone-ptfe-products-48-4.jpeg", "/images/catalogue/rubber-silicone-ptfe-products-48-5.jpeg", "/images/catalogue/rubber-silicone-ptfe-products-48-6.jpeg", "/images/catalogue/rubber-silicone-ptfe-products-48-7.jpeg", "/images/catalogue/rubber-silicone-ptfe-products-48-8.jpeg", "/images/catalogue/rubber-silicone-ptfe-products-48-9.jpeg", "/images/catalogue/rubber-silicone-ptfe-products-48-10.jpeg", "/images/catalogue/rubber-silicone-ptfe-products-48-11.jpeg", "/images/catalogue/rubber-silicone-ptfe-products-48-12.jpeg", "/images/catalogue/rubber-silicone-ptfe-products-48-13.jpeg", "/images/catalogue/rubber-silicone-ptfe-products-48-14.jpeg", "/images/catalogue/rubber-silicone-ptfe-products-48-15.jpeg", "/images/catalogue/rubber-silicone-ptfe-products-48-16.jpeg"],
      previews: ["/images/catalogue/rubber-silicone-ptfe-products-48-1.jpeg", "/images/catalogue/rubber-silicone-ptfe-products-48-2.jpeg", "/images/catalogue/rubber-silicone-ptfe-products-48-3.jpeg", "/images/catalogue/rubber-silicone-ptfe-products-48-4.jpeg", "/images/catalogue/rubber-silicone-ptfe-products-48-5.jpeg", "/images/catalogue/rubber-silicone-ptfe-products-48-6.jpeg", "/images/catalogue/rubber-silicone-ptfe-products-48-7.jpeg", "/images/catalogue/rubber-silicone-ptfe-products-48-8.jpeg", "/images/catalogue/rubber-silicone-ptfe-products-48-9.jpeg", "/images/catalogue/rubber-silicone-ptfe-products-48-10.jpeg", "/images/catalogue/rubber-silicone-ptfe-products-48-11.jpeg", "/images/catalogue/rubber-silicone-ptfe-products-48-12.jpeg", "/images/catalogue/rubber-silicone-ptfe-products-48-13.jpeg", "/images/catalogue/rubber-silicone-ptfe-products-48-14.jpeg", "/images/catalogue/rubber-silicone-ptfe-products-48-15.jpeg", "/images/catalogue/rubber-silicone-ptfe-products-48-16.jpeg"],
    },
  },
  {
    id: 49,
    title: "Lead-Free Sieves & Pharma Spares",
    category: "Sealing & Fluid Handling",
    subCategory: "Pharma Spares",
    description: "Vibro sifter sieves in SS 316L pharma quality, lead free, with and without moulding, in sizes \u00d8150, \u00d8275, \u00d8300, \u00d8550, \u00d8750, \u00d8895, \u00d8900, \u00d8915, \u00d81000, \u00d81220 and \u00d81500 mm. Vibrating springs, clamps and multimill blade and beater assemblies are available to complete the machine.",
    specifications: [
      { label: "Vibro Sifter Sieves \u2014 Moulded", value: "With moulding and without moulding" },
      { label: "Cone Sieve", value: "SS 316L pharma quality" },
      { label: "Sieve Sleeves & Ferrules", value: "SS 316L pharma quality" },
      { label: "Round Sifter Sieve", value: "SS 316L pharma quality" },
      { label: "Sieve Mesh Tube", value: "10 mesh to 400 mesh and micron grades" },
      { label: "Sieve Ring", value: "SS 316L pharma quality" },
      { label: "Tri Clamp \u2014 SS 316L", value: "Tri-clamp and hinged clamp" },
      { label: "Multimill Screen Set", value: "Blade sets, beaters, screens and shafts" },
      { label: "Standard sieve diameters", value: "\u00d8150, \u00d8275, \u00d8300, \u00d8550, \u00d8750, \u00d8895, \u00d8900, \u00d8915, \u00d81000, \u00d81220, \u00d81500 mm" },
      { label: "Bonding", value: "Food-grade adhesive, no lead soldering" },
      { label: "Documentation", value: "Material test certificate on request" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/lead-free-sieves-pharma-spares-49-1.jpeg", "/images/catalogue/lead-free-sieves-pharma-spares-49-2.jpeg", "/images/catalogue/lead-free-sieves-pharma-spares-49-3.jpeg", "/images/catalogue/lead-free-sieves-pharma-spares-49-4.jpeg", "/images/catalogue/lead-free-sieves-pharma-spares-49-5.jpeg", "/images/catalogue/lead-free-sieves-pharma-spares-49-6.jpeg", "/images/catalogue/lead-free-sieves-pharma-spares-49-7.jpeg", "/images/catalogue/lead-free-sieves-pharma-spares-49-8.jpeg"],
      previews: ["/images/catalogue/lead-free-sieves-pharma-spares-49-1.jpeg", "/images/catalogue/lead-free-sieves-pharma-spares-49-2.jpeg", "/images/catalogue/lead-free-sieves-pharma-spares-49-3.jpeg", "/images/catalogue/lead-free-sieves-pharma-spares-49-4.jpeg", "/images/catalogue/lead-free-sieves-pharma-spares-49-5.jpeg", "/images/catalogue/lead-free-sieves-pharma-spares-49-6.jpeg", "/images/catalogue/lead-free-sieves-pharma-spares-49-7.jpeg", "/images/catalogue/lead-free-sieves-pharma-spares-49-8.jpeg"],
    },
  },
  {
    id: 50,
    title: "Wiring Devices & Modular Switches",
    category: "Electrical & Power Systems",
    subCategory: "Wiring Accessories",
    description: "Modular plate systems for premium residential, commercial and hospitality interiors, together with industrial-grade sockets, weatherproof enclosures and floor boxes.",
    specifications: [
      { label: "Metal Finish Modular Switch", value: "Premium modular range" },
      { label: "Textured Modular Plate", value: "Premium modular range" },
      { label: "Designer Plate Finishes", value: "Premium modular range" },
      { label: "Champagne Gold Plate", value: "Premium modular range" },
      { label: "White Modular Switch Plate", value: "Commercial & utility range" },
      { label: "Floor Pop-Up Box", value: "Commercial & utility range" },
      { label: "Weatherproof Socket Enclosure", value: "Commercial & utility range" },
      { label: "Industrial Panel Socket", value: "Commercial & utility range" },
      { label: "Industrial Plug & Coupler", value: "Industrial connection" },
      { label: "Busbar Trunking System", value: "Industrial connection" },
      { label: "Floor Raceway", value: "Industrial connection" },
      { label: "Timer & Occupancy Control", value: "Industrial connection" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/wiring-devices-modular-switches-50-1.jpeg", "/images/catalogue/wiring-devices-modular-switches-50-2.jpeg", "/images/catalogue/wiring-devices-modular-switches-50-3.jpeg", "/images/catalogue/wiring-devices-modular-switches-50-4.jpeg", "/images/catalogue/wiring-devices-modular-switches-50-5.jpeg", "/images/catalogue/wiring-devices-modular-switches-50-6.jpeg", "/images/catalogue/wiring-devices-modular-switches-50-7.jpeg", "/images/catalogue/wiring-devices-modular-switches-50-8.jpeg", "/images/catalogue/wiring-devices-modular-switches-50-9.jpeg", "/images/catalogue/wiring-devices-modular-switches-50-10.jpeg", "/images/catalogue/wiring-devices-modular-switches-50-11.jpeg", "/images/catalogue/wiring-devices-modular-switches-50-12.jpeg"],
      previews: ["/images/catalogue/wiring-devices-modular-switches-50-1.jpeg", "/images/catalogue/wiring-devices-modular-switches-50-2.jpeg", "/images/catalogue/wiring-devices-modular-switches-50-3.jpeg", "/images/catalogue/wiring-devices-modular-switches-50-4.jpeg", "/images/catalogue/wiring-devices-modular-switches-50-5.jpeg", "/images/catalogue/wiring-devices-modular-switches-50-6.jpeg", "/images/catalogue/wiring-devices-modular-switches-50-7.jpeg", "/images/catalogue/wiring-devices-modular-switches-50-8.jpeg", "/images/catalogue/wiring-devices-modular-switches-50-9.jpeg", "/images/catalogue/wiring-devices-modular-switches-50-10.jpeg", "/images/catalogue/wiring-devices-modular-switches-50-11.jpeg", "/images/catalogue/wiring-devices-modular-switches-50-12.jpeg"],
    },
  },
  {
    id: 51,
    title: "Protection Devices & Distribution",
    category: "Electrical & Power Systems",
    subCategory: "Switchgear",
    description: "Low-voltage protection and distribution \u2014 air circuit breakers through to final distribution boards, selected for the fault level and discrimination the installation actually requires.",
    specifications: [
      { label: "Air Circuit Breaker (ACB)", value: "630 A to 6300 A, fixed and draw-out" },
      { label: "Miniature Circuit Breaker (MCB)", value: "0.5 \u2013 63 A, single to four pole, B/C/D curve" },
      { label: "Residual Current Circuit Breaker (RCCB)", value: "25 A to 100 A, two and four pole" },
      { label: "Residual Current Breaker with Overload (RCBO)", value: "Combined RCD and overload protection" },
      { label: "SPN / TPN Distribution Board", value: "Indoor IP42 to weatherproof IP65" },
      { label: "VTPN Distribution Board", value: "Vertical TPN range" },
      { label: "Plug & Socket Enclosure", value: "Industrial enclosure range" },
      { label: "Busbar Rising Main", value: "Sandwich and air-insulated, up to 5000 A" },
      { label: "MCB breaking capacity", value: "10 kA / 6 kA to IS/IEC 60898" },
      { label: "RCCB sensitivity", value: "30 mA, 100 mA and 300 mA" },
      { label: "MCCB frame sizes", value: "16 A to 630 A, fixed and adjustable" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/protection-devices-distribution-51-1.jpeg", "/images/catalogue/protection-devices-distribution-51-2.jpeg", "/images/catalogue/protection-devices-distribution-51-3.jpeg", "/images/catalogue/protection-devices-distribution-51-4.jpeg", "/images/catalogue/protection-devices-distribution-51-5.jpeg", "/images/catalogue/protection-devices-distribution-51-6.jpeg", "/images/catalogue/protection-devices-distribution-51-7.jpeg", "/images/catalogue/protection-devices-distribution-51-8.jpeg"],
      previews: ["/images/catalogue/protection-devices-distribution-51-1.jpeg", "/images/catalogue/protection-devices-distribution-51-2.jpeg", "/images/catalogue/protection-devices-distribution-51-3.jpeg", "/images/catalogue/protection-devices-distribution-51-4.jpeg", "/images/catalogue/protection-devices-distribution-51-5.jpeg", "/images/catalogue/protection-devices-distribution-51-6.jpeg", "/images/catalogue/protection-devices-distribution-51-7.jpeg", "/images/catalogue/protection-devices-distribution-51-8.jpeg"],
    },
  },
  {
    id: 52,
    title: "LED Lighting \u2014 Industrial & Outdoor",
    category: "Electrical & Power Systems",
    subCategory: "Illumination",
    description: "High-bay, flood and street luminaires for plant, yard and roadway lighting, with pole, high-mast and landscape hardware to complete the installation.",
    specifications: [
      { label: "LED High Bay \u2014 Round", value: "High bay & industrial" },
      { label: "LED High Bay \u2014 Reflector", value: "High bay & industrial" },
      { label: "LED Well Glass Fitting", value: "High bay & industrial" },
      { label: "Industrial Bay Luminaire", value: "High bay & industrial" },
      { label: "LED Street Light", value: "Street & flood" },
      { label: "LED Street Light \u2014 Cast Housing", value: "Street & flood" },
      { label: "LED Flood Light", value: "Street & flood" },
      { label: "LED Flood Light \u2014 Modular Array", value: "Street & flood" },
      { label: "Lighting Poles", value: "Poles, masts & landscape" },
      { label: "High Mast Lighting", value: "Poles, masts & landscape" },
      { label: "Bollard Light", value: "Poles, masts & landscape" },
      { label: "Spike / Garden Light", value: "Poles, masts & landscape" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/led-lighting-industrial-outdoor-52-1.jpeg", "/images/catalogue/led-lighting-industrial-outdoor-52-2.jpeg", "/images/catalogue/led-lighting-industrial-outdoor-52-3.jpeg", "/images/catalogue/led-lighting-industrial-outdoor-52-4.jpeg", "/images/catalogue/led-lighting-industrial-outdoor-52-5.jpeg", "/images/catalogue/led-lighting-industrial-outdoor-52-6.jpeg", "/images/catalogue/led-lighting-industrial-outdoor-52-7.jpeg", "/images/catalogue/led-lighting-industrial-outdoor-52-8.jpeg", "/images/catalogue/led-lighting-industrial-outdoor-52-9.jpeg", "/images/catalogue/led-lighting-industrial-outdoor-52-10.jpeg", "/images/catalogue/led-lighting-industrial-outdoor-52-11.jpeg", "/images/catalogue/led-lighting-industrial-outdoor-52-12.jpeg"],
      previews: ["/images/catalogue/led-lighting-industrial-outdoor-52-1.jpeg", "/images/catalogue/led-lighting-industrial-outdoor-52-2.jpeg", "/images/catalogue/led-lighting-industrial-outdoor-52-3.jpeg", "/images/catalogue/led-lighting-industrial-outdoor-52-4.jpeg", "/images/catalogue/led-lighting-industrial-outdoor-52-5.jpeg", "/images/catalogue/led-lighting-industrial-outdoor-52-6.jpeg", "/images/catalogue/led-lighting-industrial-outdoor-52-7.jpeg", "/images/catalogue/led-lighting-industrial-outdoor-52-8.jpeg", "/images/catalogue/led-lighting-industrial-outdoor-52-9.jpeg", "/images/catalogue/led-lighting-industrial-outdoor-52-10.jpeg", "/images/catalogue/led-lighting-industrial-outdoor-52-11.jpeg", "/images/catalogue/led-lighting-industrial-outdoor-52-12.jpeg"],
    },
  },
  {
    id: 53,
    title: "LED Lighting \u2014 Commercial & Interior",
    category: "Electrical & Power Systems",
    subCategory: "Illumination",
    description: "Panels, downlighters, battens and decorative fittings for offices, retail, hospitality and residential interiors.",
    specifications: [
      { label: "Surface Downlighter", value: "Commercial range" },
      { label: "2 \u00d7 2 LED Panel", value: "Commercial range" },
      { label: "Suspended Linear Batten", value: "Commercial range" },
      { label: "Recessed Panel \u2014 Square & Round", value: "Commercial range" },
      { label: "Bulkhead Luminaire", value: "Utility & weatherproof" },
      { label: "Weatherproof Batten", value: "Utility & weatherproof" },
      { label: "LED Batten", value: "Utility & weatherproof" },
      { label: "LED Bulb", value: "Utility & weatherproof" },
      { label: "Heritage Lamp Post", value: "Decorative & portable" },
      { label: "Post Top Lantern", value: "Decorative & portable" },
      { label: "Rechargeable Security Light", value: "Decorative & portable" },
      { label: "Emergency Lighting Unit", value: "Decorative & portable" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/led-lighting-commercial-interior-53-1.jpeg", "/images/catalogue/led-lighting-commercial-interior-53-2.jpeg", "/images/catalogue/led-lighting-commercial-interior-53-3.jpeg", "/images/catalogue/led-lighting-commercial-interior-53-4.jpeg", "/images/catalogue/led-lighting-commercial-interior-53-5.jpeg", "/images/catalogue/led-lighting-commercial-interior-53-6.jpeg", "/images/catalogue/led-lighting-commercial-interior-53-7.jpeg", "/images/catalogue/led-lighting-commercial-interior-53-8.jpeg", "/images/catalogue/led-lighting-commercial-interior-53-9.jpeg", "/images/catalogue/led-lighting-commercial-interior-53-10.jpeg", "/images/catalogue/led-lighting-commercial-interior-53-11.jpeg", "/images/catalogue/led-lighting-commercial-interior-53-12.jpeg"],
      previews: ["/images/catalogue/led-lighting-commercial-interior-53-1.jpeg", "/images/catalogue/led-lighting-commercial-interior-53-2.jpeg", "/images/catalogue/led-lighting-commercial-interior-53-3.jpeg", "/images/catalogue/led-lighting-commercial-interior-53-4.jpeg", "/images/catalogue/led-lighting-commercial-interior-53-5.jpeg", "/images/catalogue/led-lighting-commercial-interior-53-6.jpeg", "/images/catalogue/led-lighting-commercial-interior-53-7.jpeg", "/images/catalogue/led-lighting-commercial-interior-53-8.jpeg", "/images/catalogue/led-lighting-commercial-interior-53-9.jpeg", "/images/catalogue/led-lighting-commercial-interior-53-10.jpeg", "/images/catalogue/led-lighting-commercial-interior-53-11.jpeg", "/images/catalogue/led-lighting-commercial-interior-53-12.jpeg"],
    },
  },
  {
    id: 54,
    title: "Cables & Wires",
    category: "Electrical & Power Systems",
    subCategory: "Power Transmission",
    description: "Armoured and unarmoured power cables, control and instrumentation cables, house wiring and communication cable, sized and specified to installation conditions.",
    specifications: [
      { label: "Cu / Al Armoured Cable", value: "Power cable" },
      { label: "Multicore Power Cable", value: "Power cable" },
      { label: "Multicore Flexible Cable", value: "Power cable" },
      { label: "Control & Instrumentation Cable", value: "Power cable" },
      { label: "House Wire \u2014 FR / FRLS", value: "Building & communication" },
      { label: "Twin Flat / Speaker Cable", value: "Building & communication" },
      { label: "Busbar Trunking", value: "Building & communication" },
      { label: "Under-Carpet Raceway", value: "Building & communication" },
      { label: "Conductor", value: "Electrolytic grade copper and aluminium" },
      { label: "Power cable sizes", value: "1.5 to 630 sq mm, single and multicore" },
      { label: "Voltage grades", value: "1100 V, 3.3 kV, 6.6 kV and 11 kV" },
      { label: "Standards", value: "IS 694, IS 1554, IS 7098 and equivalents" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/cables-wires-54-1.jpeg", "/images/catalogue/cables-wires-54-2.jpeg", "/images/catalogue/cables-wires-54-3.jpeg", "/images/catalogue/cables-wires-54-4.jpeg", "/images/catalogue/cables-wires-54-5.jpeg", "/images/catalogue/cables-wires-54-6.jpeg", "/images/catalogue/cables-wires-54-7.jpeg", "/images/catalogue/cables-wires-54-8.jpeg"],
      previews: ["/images/catalogue/cables-wires-54-1.jpeg", "/images/catalogue/cables-wires-54-2.jpeg", "/images/catalogue/cables-wires-54-3.jpeg", "/images/catalogue/cables-wires-54-4.jpeg", "/images/catalogue/cables-wires-54-5.jpeg", "/images/catalogue/cables-wires-54-6.jpeg", "/images/catalogue/cables-wires-54-7.jpeg", "/images/catalogue/cables-wires-54-8.jpeg"],
    },
  },
  {
    id: 55,
    title: "Power Backup & Conditioning",
    category: "Electrical & Power Systems",
    subCategory: "Power Systems",
    description: "Three-phase online UPS, servo voltage stabilizers, harmonic filters, static transfer switches, inverters and batteries for continuous and clean power.",
    specifications: [
      { label: "3 Phase Online UPS \u2014 Compact", value: "UPS & static switching" },
      { label: "3 Phase Online UPS \u2014 Modular", value: "UPS & static switching" },
      { label: "Static Transfer Switch", value: "UPS & static switching" },
      { label: "Active Harmonic Filter", value: "UPS & static switching" },
      { label: "Air Cooled Servo Stabilizer", value: "Servo voltage stabilizers" },
      { label: "Oil Cooled Servo Stabilizer", value: "Servo voltage stabilizers" },
      { label: "Industrial Servo Stabilizer", value: "Servo voltage stabilizers" },
      { label: "Single Phase Stabilizer", value: "Servo voltage stabilizers" },
      { label: "Home Inverter", value: "Inverters & batteries" },
      { label: "Smart UPS Inverter", value: "Inverters & batteries" },
      { label: "Sine Wave Inverter", value: "Inverters & batteries" },
      { label: "Tubular Battery", value: "Inverters & batteries" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/power-backup-conditioning-55-1.jpeg", "/images/catalogue/power-backup-conditioning-55-2.jpeg", "/images/catalogue/power-backup-conditioning-55-3.jpeg", "/images/catalogue/power-backup-conditioning-55-4.jpeg", "/images/catalogue/power-backup-conditioning-55-5.jpeg", "/images/catalogue/power-backup-conditioning-55-6.jpeg", "/images/catalogue/power-backup-conditioning-55-7.jpeg", "/images/catalogue/power-backup-conditioning-55-8.jpeg", "/images/catalogue/power-backup-conditioning-55-9.jpeg", "/images/catalogue/power-backup-conditioning-55-10.jpeg", "/images/catalogue/power-backup-conditioning-55-11.jpeg", "/images/catalogue/power-backup-conditioning-55-12.jpeg"],
      previews: ["/images/catalogue/power-backup-conditioning-55-1.jpeg", "/images/catalogue/power-backup-conditioning-55-2.jpeg", "/images/catalogue/power-backup-conditioning-55-3.jpeg", "/images/catalogue/power-backup-conditioning-55-4.jpeg", "/images/catalogue/power-backup-conditioning-55-5.jpeg", "/images/catalogue/power-backup-conditioning-55-6.jpeg", "/images/catalogue/power-backup-conditioning-55-7.jpeg", "/images/catalogue/power-backup-conditioning-55-8.jpeg", "/images/catalogue/power-backup-conditioning-55-9.jpeg", "/images/catalogue/power-backup-conditioning-55-10.jpeg", "/images/catalogue/power-backup-conditioning-55-11.jpeg", "/images/catalogue/power-backup-conditioning-55-12.jpeg"],
    },
  },
  {
    id: 56,
    title: "Pumps, Motors & Building Services",
    category: "Electrical & Power Systems",
    subCategory: "Rotating & Comfort",
    description: "Pump sets and three-phase motors for utility duty, together with water heating, ventilation and comfort equipment for plant amenity and residential projects.",
    specifications: [
      { label: "Monoblock Pump Set", value: "Pumps & motors" },
      { label: "Pressure Booster Pump", value: "Pumps & motors" },
      { label: "3 Phase Induction Motor", value: "Pumps & motors" },
      { label: "Control & Starter Unit", value: "Pumps & motors" },
      { label: "Storage Water Heater", value: "Water heating & ventilation" },
      { label: "Solar Water Heater", value: "Water heating & ventilation" },
      { label: "Ventilation Fan", value: "Water heating & ventilation" },
      { label: "BLDC Ceiling Fan", value: "Water heating & ventilation" },
      { label: "Wall Mounting Fan", value: "Comfort & appliances" },
      { label: "Desert Air Cooler", value: "Comfort & appliances" },
      { label: "Mixer Grinder", value: "Comfort & appliances" },
      { label: "Room Heater", value: "Comfort & appliances" },
    ],
    imgs: {
      thumbnails: ["/images/catalogue/pumps-motors-building-services-56-1.jpeg", "/images/catalogue/pumps-motors-building-services-56-2.jpeg", "/images/catalogue/pumps-motors-building-services-56-3.jpeg", "/images/catalogue/pumps-motors-building-services-56-4.jpeg", "/images/catalogue/pumps-motors-building-services-56-5.jpeg", "/images/catalogue/pumps-motors-building-services-56-6.jpeg", "/images/catalogue/pumps-motors-building-services-56-7.jpeg", "/images/catalogue/pumps-motors-building-services-56-8.jpeg", "/images/catalogue/pumps-motors-building-services-56-9.jpeg", "/images/catalogue/pumps-motors-building-services-56-10.jpeg", "/images/catalogue/pumps-motors-building-services-56-11.jpeg", "/images/catalogue/pumps-motors-building-services-56-12.jpeg"],
      previews: ["/images/catalogue/pumps-motors-building-services-56-1.jpeg", "/images/catalogue/pumps-motors-building-services-56-2.jpeg", "/images/catalogue/pumps-motors-building-services-56-3.jpeg", "/images/catalogue/pumps-motors-building-services-56-4.jpeg", "/images/catalogue/pumps-motors-building-services-56-5.jpeg", "/images/catalogue/pumps-motors-building-services-56-6.jpeg", "/images/catalogue/pumps-motors-building-services-56-7.jpeg", "/images/catalogue/pumps-motors-building-services-56-8.jpeg", "/images/catalogue/pumps-motors-building-services-56-9.jpeg", "/images/catalogue/pumps-motors-building-services-56-10.jpeg", "/images/catalogue/pumps-motors-building-services-56-11.jpeg", "/images/catalogue/pumps-motors-building-services-56-12.jpeg"],
    },
  },
];

export default shopData;